### ISSUE TITLE
WayScript Bug Report - Slack new channel trigger

### ISSUE THREAD

**Issue by lukasab** [wayscript/feedback#11]
**Describe the bug**
Slack Trigger when a new channel is created not working. The values (Slack_channel, Slack_user, and JSON_Data) are not getting parsed or not triggering. 

**To Reproduce**
1. Create a new Slack Trigger when a new channel is created
2. Select "Any channel" 
3. Select all outputs
4. Create print with all outputs
5. Create a new slack channel
5. See error (no log)

**Expected behavior**
Expected to see all outputs.

**Screenshots**
![image](https://user-images.githubusercontent.com/16520334/77563037-0a5f9080-6ec1-11ea-95a6-5f80fcfc6dab.png)

**Desktop (please complete the following information):**
 - OS: UBUNTU
 - Browser: Chrome
 - Version: 79.0.3945.117 (Official Build) (64-bit)

**Additional context**
I tried using the slack trigger with new message and it worked.

**Comment by jeffbuswell** [comment]
Hello, we appear to have missed this issue. We are investigating. Apologies for the delay. Please reach out on our Discord server for additional updates.

**Comment by jeffbuswell** [comment]
Closing stale WayScript Viz issues
