### ISSUE TITLE
Monday.com integration WayScript Feature Request

### ISSUE THREAD

**Issue by sajanjacob** [wayscript/feedback#12]
**Is your feature request related to a problem? Please describe.**
My work uses monday.com and slack and I'd like to be able to seemlessly connect the two apps.

**What's your idea?**
A monday.com integration / package.

**Describe alternatives you've considered**
I've looked at Zapier & automate.io and their functionality between Slack/Monday.com is limited.

**Additional context**
N/A

**Comment by jorshman** [comment]
Hi @m3tamusic  - We have added a monday.com integration to WayScript
