### ISSUE TITLE
WayScript Bug Report

### ISSUE THREAD

**Issue by supportbboxx** [wayscript/feedback#13]
**Description**
I have created a code to export all users in Office365 using headless selenium, it was working perfectly on my end but when I paste the code in wayscript it doesn't work. 

**To Reproduce**
I have added a code that will print screen inside the selenium then upload it to my SharePoint so I can see where I'm stuck at.
```
print (browser.current_url)
browser.save_screenshot("bebe.png")
```
As you can see I also printed all the files inside the directory but was not unable to find the csv. file which should be downloaded after clicking the export button.
![image](https://user-images.githubusercontent.com/57546408/81328334-4ba5ab80-90cf-11ea-9645-7a2812560f7b.png)
As you can see in this screenshot, this is where I am stuck at.
![image](https://user-images.githubusercontent.com/57546408/81328163-01bcc580-90cf-11ea-8f6b-bc6077597c3c.png)

**Expected behavior**
Click the export button.

**Screenshots**
![image](https://user-images.githubusercontent.com/57546408/81328451-83145800-90cf-11ea-8a47-13227e9a1998.png)

**Comment by jorshman** [comment]
@iguinto do your selenium options match this: https://docs.wayscript.com/library/modules/python/libraries#using-selenium

**Comment by jorshman** [comment]
@iguinto - currently, you cannot export/impot a csv into your python module (this is a feature coming soon). In order to do this currently, you need to [export that data as a data structure](https://docs.wayscript.com/library/modules/python#outputs) and pass the value to the [CSV module to write](https://docs.wayscript.com/library/modules/csv#write-file).

**Comment by supportbboxx** [comment]
Hi @jorshman,

I confirmed that my selenium option was matched to the link you provided.
I was able to export a csv file. 
I already created a code for exporting all users in slack which download a csv file and then upload it to my sharepoint.

**Comment by jorshman** [comment]
@iguinto - just to confirm, you got it working or there is still an issue you are having?

**Comment by supportbboxx** [comment]
@jorshman,

It was working but not working as it used to be.
![image](https://user-images.githubusercontent.com/57546408/81335829-cf18ca00-90da-11ea-9b43-f1bdb4fbbe40.png)
this code should click this element
![image](https://user-images.githubusercontent.com/57546408/81337518-b231c600-90dd-11ea-9d7b-06d8f7e4fee5.png)

**Comment by jorshman** [comment]
I see - it is a bit hard to know if there is a WayScript issue or if something on the Microsoft365 side changed. Can you confirm through the page html that the selenium browser is on the correct page and that the popup is opened?

**Comment by supportbboxx** [comment]
Yes, the selenium headless browser is on the correct page.  
![image](https://user-images.githubusercontent.com/57546408/81341687-8960ff00-90e4-11ea-8ad2-3f27f1163262.png)
![image](https://user-images.githubusercontent.com/57546408/81341752-a564a080-90e4-11ea-84d7-25f39b82ed77.png)
This is the updated screenshot where it stuck.
![image](https://user-images.githubusercontent.com/57546408/81341899-ec529600-90e4-11ea-9ed0-fd3168839f19.png)

**Comment by supportbboxx** [comment]
If I need to add additional information please let me know.

Regards,
Ian

**Comment by jorshman** [comment]
Just shooting in the dark a little since I can't run the script. Can you try 'find_element_by_xpath' and pass the xpath instead of the classname? Also - if you do 'find_element**s**_by_classname' are there more than one? If so, it might be that it is clicking the wrong one.

**Comment by supportbboxx** [comment]
I already tried all class and xpath but still no luck :(
The screenshot below is the element I tried.
Is it possible if I can share my desktop? or talk to you on live? 
![image](https://user-images.githubusercontent.com/57546408/81432472-8ffb7f00-9195-11ea-920c-1bfec831fabb.png)

**Comment by supportbboxx** [comment]
![image](https://user-images.githubusercontent.com/57546408/81432578-c33e0e00-9195-11ea-8f14-2eb3fee16ab5.png)

**Comment by jorshman** [comment]
Yes - can you email me at jesse[at]wayscript.com and we can find a time to speak live? Also - you can message me on our discord forum.

**Comment by jorshman** [comment]
@iguinto how long do you think your script runs for? We recently added a 5min runtime limit in the free (non-premium) tiers.

**Comment by supportbboxx** [comment]
Hi @jorshman ,

Do you mind sending the discord link as I cannot send a message on discord inside the wayscript website.
The script usually runs for 3minutes

Regards,
Ian

**Comment by jorshman** [comment]
@iguinto 
Here is the [discord link](https://discord.gg/nchf9E9). 

Also - lets find a time for a real time video call so I can help debug this!

**Comment by supportbboxx** [comment]
Hi @jorshman,

This is now has been resolved, thank you Jorsh
