### ISSUE TITLE
WayScript Feedback

### ISSUE THREAD

**Issue by GabCores** [wayscript/feedback#14]
loving too much , getting confidence with the product 
looking to integrate with CRMs , like Zoho CRM . I have to wait? - traditional way in some other integrators- or I am/ will be able to do it on myself ?
Thanks for building
Regards

**Comment by jeffbuswell** [comment]
@GabrielGab We'd be happy to add Zoho CRM integration. We'll try to do it in the next week or so. Will keep you posted!
