### ISSUE TITLE
[FR] Telegram bot

### ISSUE THREAD

**Issue by bestpika** [wayscript/feedback#16]
**Is your feature request related to a problem? Please describe.**

I send RSS to chats/channels/groups via Telegram bot, but at the moment I have to compose my own strings and send them via request as there is no module for this, so I'm hoping to add this feature.

**What's your idea?**

I hope this module can implement getUpdates, sendMessage and sendPhoto.

**Describe alternatives you've considered**

I write the code in JavaScript and use requests to send messages to the Telegram bot api to myself.

**Additional context**

ref. <https://core.telegram.org/bots/api#getupdates>
ref. <https://core.telegram.org/bots/api#sendmessage>
ref. <https://core.telegram.org/bots/api#sendphoto>

**Comment by jeffbuswell** [comment]
This has been added to our backlog.
