### ISSUE TITLE
WayScript Feature Request

### ISSUE THREAD

**Issue by matt-atadata** [wayscript/feedback#20]
**Is your feature request related to a problem? Please describe.**
I'm trying to build a workflow around Github Actions.

**What's your idea?**
I would like to see the github module extended to more easily pull in files and manage all actions/workflows from github.

**Describe alternatives you've considered**
AWS Lambda or GCP Cloud Functions

**Additional context**
Really help to control and build my CICD.

**Comment by jeffbuswell** [comment]
This has been added to our backlog. Thanks!
