### ISSUE TITLE
Time Trigger module with ambiguous icon

### ISSUE THREAD

**Issue by allenabc** [wayscript/feedback#21]
**Describe the bug**
The "Time Trigger" doesn't fire unless it's switched ON AND the Double arrows don't have the additional red dot

**To Reproduce**
I used the Execute Shell Script community example
1. Change the time
2. Notice the circular arrows have a small red dot
3. Unless you click on the dot the timer doesn't fire at the assigned time.

**Expected behavior**
The problem with any Cron job is that you may need to run it after hours. You will not be around to see that it doesn't work it just mysteriously fails. It should be more obvious that the job will not fire at the appointed time. The presence of tiny red dot isn't obvious. A warning about Time Trigger is disabled perhaps or the slider with enabled on one side and disabled on the other.

**Screenshots**

Trigger ON
![triggerOn](https://user-images.githubusercontent.com/2830668/117603352-b127e000-b107-11eb-8841-deead12bc3c7.png)

Trigger OFF
![triggerOff](https://user-images.githubusercontent.com/2830668/117603365-b7b65780-b107-11eb-9ffd-2051c9800535.png)

**Desktop (please complete the following information):**
 Ubuntu 20.4

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by jeffbuswell** [comment]
Closing stale WayScript Viz issues
