### ISSUE TITLE
WayScript Bug Report

### ISSUE THREAD

**Issue by sigmet** [wayscript/feedback#22]
**Describe the bug**
Passings args to a function on a different script fails.

**To Reproduce**
1. Create two scripts (a and b). B as an input field.
2. Invoke B.main from A.Main with struct as an arg. 
3. Script B.main invokes normally but without args
4. Bug is reproduced 

**Expected behavior**
B.main should invoke with args (data type: struct) in variables dict.

**Comment by jeffbuswell** [comment]
Closing stale WayScript Viz issues
