### ISSUE TITLE
Alexa Skill Enable in India [WayScript Feature Request]

### ISSUE THREAD

**Issue by nilava** [wayscript/feedback#3]
Hey guys, i really like the platform! It would be great if you also distribute the Alexa Skill in India![English(IN)]

**Comment by jeffbuswell** [comment]
Hi @nilava, Thanks for the suggestion! We'll work on getting the Alexa skill released in India as soon as possible.

**Comment by jeffbuswell** [comment]
@nilava The WayScript Alexa Skill is now available in English (IN), English (CA), English (GB), English (AU), and English (US)!

Thanks for your feedback!
