### ISSUE TITLE
WayScript Feature Request - Airbnb Module

### ISSUE THREAD

**Issue by dplakon** [wayscript/feedback#5]
**What's your idea?**
An Airbnb module! I would love to automate check in information messages to my guests when they book my vacation rental.

**Comment by jeffbuswell** [comment]
@dplakon That sounds like an awesome use case, we'll look into it. Thanks for the suggestion!

**Comment by jeffbuswell** [comment]
@dplakon Would you still want an AirBnb module, given you now have this program:
https://wayscript.com/shared/5r2JCwDd

**Comment by jeffbuswell** [comment]
@dplakon closing this so we can take it offline
