### ISSUE TITLE
Unable to authorize outlook account

### ISSUE THREAD

**Issue by supportbboxx** [wayscript/feedback#7]
Unable to authorized my outlook account.

Add a step > Add Outlook.
Select an Account > Add an account.
After adding the account this error will pop up:
Account Could not be authorized

Expected Output:
To be able to add my outlook account

![image](https://user-images.githubusercontent.com/57546408/68968682-192f8b80-07db-11ea-8129-4b3d3d8cff12.png)

 - OS: Windows 10
 - Browser: Chrome

I've already tried to used different browsers and turn off my outlook account security permission but I still cannot connect my account.

**Comment by jeffbuswell** [comment]
@iguinto Thanks for reporting this issue.

I am unable to reproduce what you are seeing. When you click "add an account," are you taken to the Microsoft live login screen? Does that screen prompt you to allow WayScript to access your account, then redirect you back to WayScript?

**Comment by supportbboxx** [comment]
HI @jeffbuswell, Yes, but after logging in to my Microsoft account successfully it will redirect me back to  Wayscript and the error will pop up.

**Comment by jeffbuswell** [comment]
@iguinto We made some changes to this flow yesterday. Do you mind giving it another shot?

**Comment by supportbboxx** [comment]
Hi @jeffbuswell,

Still having the same issue.
