### ISSUE TITLE
WayScript Feature Request

### ISSUE THREAD

**Issue by cdawizard** [wayscript/feedback#8]
Would like to see WayScript add integrations modules for mysms & google contacts. So automations can be made between airtable and the following apps google calendar, google contacts, & mysms.  Look forward to being able to create automation between those apps...

The object is to pass data between airtable & google contacts when a update is made. Create triggers to send custom text messages using airtable & sending them using mysms at scheduled times.

**Comment by jeffbuswell** [comment]
Thanks for the feedback! We'll look into adding these modules in the future.
