### ISSUE TITLE
WayScript Feedback

### ISSUE THREAD

**Issue by joeygold** [wayscript/feedback#9]
Question
I would like to run  a MQTT client in Python on Wayscript  https://pypi.org/project/paho-mqtt/

Do  I just addin the Wayscript requirements.txt   paho-mqtt

In this way,  I can connect to my physical wireless device system that has MQTT broker and Execute Wayscripts.

**Comment by jeffbuswell** [comment]
Hello! Yes, you should be able to just add `paho-mqtt` to `requirements.txt`

**Comment by jeffbuswell** [comment]
Closing this for now. Please reach out on Discord if you have more questions!
